// ======================================================================
// BRANDING — the one file to edit when you fork this.
//
// TUNO is ENCA's sister tool (enca.limon-it.nl) and follows the same rules:
// everything the site shows about *who made it* lives here — product name,
// organisation, logos, colours, footer. Nothing else in the app hard-codes
// them; index.html carries this file's defaults as plain markup so the page
// still reads correctly before JavaScript runs, and applyBranding()
// (js/app.js) overwrites it from this object at start-up.
//
// To rebrand a fork:
//   1. Edit the fields below.
//   2. Drop your own SVG/PNG into assets/ and point `logo` and `favicon` at
//      them (a 1:1 mark works best — it is drawn at 34px and 76px).
//   3. Set `clientId` in js/authConfig.js to YOUR Entra app registration and
//      put your own host in its redirect URIs (New-TunoAppRegistration.ps1
//      does both for you).
//   4. Put your host in the CNAME file if you publish on GitHub Pages.
//
// What is deliberately NOT here:
//   · Exports (Markdown/XML) stay neutral by design — they carry the
//     customer's content, never the tool's. Only a one-line "generated by"
//     credit is added, built from `name` and `host` below.
// ======================================================================
const BRANDING = {
  // Product
  name: "TUNO",                                    // short name, shown in the header chip and footer
  longName: "Intune Operations Tools",             // descriptive line next to it
  expansion: "Tenant Utilities for iNtune Operations", // what the short name stands for ("" to hide)

  // Organisation
  org: "Limon-IT",
  // The org name is drawn as two parts so the second half can take the accent
  // colour ("Limon-<span>IT</span>"). Set `orgSplit` to "" for one flat word.
  orgSplit: "IT",
  orgUrl: "https://limon-it.nl",
  copyright: "© 2026 Limon-IT",

  // Where this deployment lives. Shown in the header and in the one-line
  // credit at the bottom of every Markdown export. No protocol.
  host: "tuno.limon-it.nl",

  // Assets (relative to index.html)
  logo: "assets/logo-mark-light.svg",
  logoDark: "assets/logo-mark-dark.svg",
  favicon: "assets/favicon.svg",

  // Sign-in screen
  loginTitle: "",            // "" → `${name} — ${longName}`
  loginBlurb: "Sign in with your Microsoft Entra account to analyze, build and validate your endpoint security configuration — starting with AppLocker policies.",

  // Optional colour overrides, written straight onto :root as CSS variables.
  // Leave empty to keep the stylesheet's palette (the Limon-IT greens, shared
  // with ENCA). css/app.css has the full set.
  colors: {},
};

// ======================================================================
// Per-audience looks. Same mechanism as ENCA: when the signed-in account's
// UPN matches an override, the app's CHROME switches to that audience's
// brand. TUNO starts with none — add entries the way ENCA's branding.js
// documents when the first customer needs one.
// ======================================================================
const BRAND_OVERRIDES = [];
const BrandOverrides = {
  forUpn: (upn) => BRAND_OVERRIDES.find((o) => o.match.test(String(upn || ""))) || null,
  byKey: (k) => BRAND_OVERRIDES.find((o) => o.key === k) || null,
};

// Small helpers so no other file has to assemble these strings. Every export
// footer and on-screen credit goes through here.
let ACTIVE_BRANDING = null;

const Brand = {
  // the active look, falling back to the deployment's own
  get current() { return ACTIVE_BRANDING || BRANDING; },
  setActive(b) { ACTIVE_BRANDING = b || null; },

  // "TUNO — Intune Operations Tools"
  get title() { return BRANDING.longName ? `${BRANDING.name} — ${BRANDING.longName}` : BRANDING.name; },
  // "TUNO · Intune Operations Tools · Limon-IT" — the <title>
  get pageTitle() { return [BRANDING.name, BRANDING.longName, BRANDING.org].filter(Boolean).join(" · "); },
  // "TUNO — Intune Operations Tools (tuno.limon-it.nl)"
  get credit() { return BRANDING.host ? `${Brand.title} (${BRANDING.host})` : Brand.title; },
  // The line every Markdown export ends its header with.
  generatedBy(verb) {
    const t = new Date().toISOString().replace("T", " ").slice(0, 16);
    return `${verb || "Generated"} ${t} UTC by ${Brand.credit}.`;
  },
  // Short form: "TUNO · tuno.limon-it.nl"
  get stamp() { return [BRANDING.name, BRANDING.host].filter(Boolean).join(" · "); },
};
