// ======================================================================
// Changelog — the source of truth for both the "What's new" overlay shown
// after sign-in and the full changelog page.
//
// Same discipline as ENCA's js/changelog.js (read its header for the long
// version):
//
// HOUSEKEEPING: whenever a tool is added or changed, add a NEW release
// object here for that build, in the same commit as the code — together
// with the home-tile NEW/BETA/UPDATED tag in index.html, the TOOL_VERSIONS
// bump, APP_BUILD.build + the ?v= cache-busting numbers, and js/promote.js
// when the change lands on the beta channel. One release object per build,
// holding ONLY what changed in that build; never bump an existing release's
// number to cover new work.
//
// kind: "new"      — a whole tool or capability that did not exist
//        "improved" — an existing tool got better
//        "fixed"    — something was wrong and now is not
//
// TEXT IS PLAIN TEXT. The renderer escapes it, so an HTML tag written here
// comes out as angle brackets mid-sentence (ENCA carried 228 broken tags
// before noticing). Quote a literal token — "bad" — rather than reaching
// for code, and carry emphasis in the words.
//
// Newest release first.
// ======================================================================
const CHANGELOG = [
  {
    build: 11, date: "2026-08-27", title: "The AppLocker workflow explains itself, and TUNO names the tenant you are in",
    items: [
      { kind: "improved", tool: "AppLocker builder & validator", text: "The generator's layouts are three cards, one per layout, so the choice is made by looking rather than by reading a dropdown. The gap report carries coverage with it: a finding now says what the policy does reach as well as what it misses, because a list of gaps with no denominator is a number nobody can act on." },
      { kind: "improved", tool: "AppLocker builder & validator", text: "A flood of gaps became one finding. Hundreds of rows saying the same thing about the same folder is not hundreds of problems, and reading it as such is how a real one gets buried." },
      { kind: "fixed", tool: "AppLocker builder & validator", text: "Apply is never a dead button. It either does something or says why it cannot, instead of sitting there looking available." },
      { kind: "improved", tool: "AppLocker builder & validator", text: "An applied fix changes the finding rather than only the rules, so the report you are reading keeps up with the policy you are editing. The deployed profile can be updated in place, its identity is one click away, and its version is editable at the button that writes it." },
      { kind: "fixed", tool: "AppLocker builder & validator", text: "Loop marks belong to one tenant. A station marked by hand is a claim about a specific tenant, and carrying it into another one would answer a question nobody asked." },
      { kind: "new", tool: "TUNO", text: "The header names the tenant you are signed in to. The organization is read at sign-in, so the name in the corner is the tenant's own rather than a domain guessed from your account." },
      { kind: "improved", tool: "All tools", text: "The sidebar icons are legible, and they are the same size whether the rail is folded or open. They used to change size as it folded, because the two states set the size in two places." },
      { kind: "improved", tool: "All tools", text: "The branding gear now works here, limited to your own browser. Applying a look changes it for you and for nobody else visiting the site, and the production deployment still ignores any branding file served next to it. Its real identity remains the one in the repository." },
    ],
  },
  {
    build: 10, date: "2026-08-26", title: "Production stops calling its tools beta",
    items: [
      { kind: "fixed", tool: "TUNO", text: "Every tool tile and screen wore a BETA chip that came across from the beta channel with the code — sixty of them after build 9. BETA is channel language: on the beta site it says a tool is still proving itself there, and on production it named a channel the visitor is not on. Production now speaks its own labels — NEW on the nine tools this production line first shipped in build 9, UPDATED on the six that changed in it, nothing on the rest — and the production check fails any future promotion that lets a BETA chip through." },
    ],
  },
  {
    build: 9, date: "2026-08-26", title: "Nine tools, the widened backup, and the timeline look",
    items: [
      { kind: "new", tool: "TUNO", text: "The largest promotion yet — thirty-five changes, beta builds 10357 through 10448 — and it brings nine tools to production. Assignment what-if: what a user or device would gain and lose by joining or leaving a group, exclusions and inheritance included, a simulation that says so. Assignment health: the assignments that exist and reach nobody — empty groups, deleted groups, unassigned, excluded-only, contradictions, failing deployments. Settings search: seventeen thousand definitions searched as you type, then who sets each one and to what, secrets redacted. Setting conflict scan: the same setting configured to different values by policies whose reach overlaps. Compliance report: the estate rolled up with stale as its own column and per-setting failure detail, plus the coverage section." },
      { kind: "new", tool: "TUNO", text: "The three security reads: Defender status per device, with a machine that never reported protection state as its own bucket and a search box that autocompletes from the fleet; Firewall and ASR coverage, where covered means assigned AND reaching somebody by construction; and Multi-admin approval, including the gate nobody can open — an approval policy whose approver groups hold no members. And the Windows LAPS audit, which carries the registration's first new permission in ninety-nine builds — ReadBasic deliberately, so Graph cannot return a password value through this tool at all." },
      { kind: "new", tool: "📦 Backup configuration", text: "The backup widens to twenty-four areas and proves itself: a SHA-256 per file, the manifest written into the zip last so its presence marks a backup complete, and an offline verify that names modified, missing and untracked files without a sign-in. Assignments now export to a file that imports back — same tenant only, refused outright across tenants, all-or-nothing per policy when a group has since been deleted, every write dry-run first, drift-skipped and verified by read-back. The Group Analyzer gains the assignment matrix, groups by surfaces at a glance, and per-group popups with a deep analyze." },
      { kind: "improved", tool: "All tools", text: "The change audit reads like a timeline: stat cards, colored operation dots, click-to-open events, a custom date range that says so when the thirty-day retention clamps it, and filters in a dialog built from the tenant's own data. The compliance report, assignment health, role assignments and conflict scan take the same layout — cards that filter, rows that fold open and remember. The AppLocker tool gains the fleet gap report, the audit loop strip, the events-first evidence card, a folded companion-script section and one consistent family of fix buttons." },
      { kind: "improved", tool: "TUNO", text: "Demo mode answers every tool from a fake tenant at the Graph layer, for trying TUNO without signing anything in. Self-host branding arrives with ENCA's gear. The header stops repeating itself, the home grid centres and clamps its cards, surface pickers fit and clear, group type-ahead matches any word, and the tool menu carries each tool's number. On the beta channel, the promotion queue now takes tick boxes and exports the order that produced this very build." },
    ],
  },
  {
    build: 8, date: "2026-08-24", title: "The console shell, three writers, and the App Control evidence loop",
    items: [
      { kind: "new", tool: "TUNO", text: "The console shell: a fixed left sidebar lists every tool, grouped exactly as on the home grid, reachable from anywhere once signed in — the sidebar is where you can go, the tabs are what you have open, and the highlight follows the tabs so the two cannot disagree. It folds to an icon rail with names on hover, remembers its state the way the theme does, and below 1240 pixels it steps aside for the centred column. The content column widens to 1500 pixels signed in; the sign-in screen is untouched." },
      { kind: "new", tool: "✏️ Assignment editor", text: "Bulk assignment changes, behind four gates. Add an include, add an exclusion, or remove a group across device configurations, settings catalog, compliance and administrative templates — the thing the portal makes you do one blade at a time. The pipeline is enforced by the screen: read, dry run naming each group with its member count, an automatic backup file that must exist before apply unlocks, removals confirmed by typing the group's name, then sequential writes each preceded by a fresh read — a policy someone else just edited is skipped as drifted, never overwritten — and followed by a read-back, so done is the tenant's word. Untouched assignments keep their filters. Tenant-wide targets and assignment filters can ride an add; a tenant-wide exclusion is refused because Graph has no such thing. No delete, no rename, ever." },
      { kind: "new", tool: "🧩 Assignment filters", text: "Assignment filters, read and written. Every filter in the tenant with its rule, and — after an explicit scan — which assignments actually use it, absent until scanned rather than a reassuring zero. Create, edit and delete under the editor's rules: edits stop on drift, and delete is the gate that matters — a typed-name confirmation, then a fresh tenant-side association check at the moment of the act, because deleting an in-use filter silently widens every assignment that carried it. Any reference refuses the delete; so does a check that could not run." },
      { kind: "new", tool: "📦 Backup configuration", text: "Restore, inside the backup tool. Open one of this tool's archives — or one from the PowerShell original, same layout — pick objects, and put them back: create only, never overwriting yours, each name carrying an editable Restored prefix, collisions stopped at dry run and re-checked fresh per create, everything arriving unassigned by design. Settings travel inline, compliance policies keep their scheduled actions, administrative templates bind to Microsoft's own definitions — and a template whose child write fails is rolled back rather than left half-made. Every create is verified by reading it back." },
      { kind: "new", tool: "🔐 AppLocker builder & validator", text: "The App Control events loop closes: a collector script harvests the CodeIntegrity and AppLocker event logs into a report and a bundle written where Intune's own diagnostics collection picks them up, a third Remediation pair deploys it from the browser, and the bundle uploads straight into the tool — where each blocked or audited execution is judged against the draft policy with the same evaluator as the coverage table, one recommendation per row. It replaces a collector that missed enforced MSI and script blocks entirely, swallowed every error, and silently returned zero CodeIntegrity events past a query limit." },
      { kind: "improved", tool: "TUNO", text: "Suggestions as you type, on every box that names a directory object: groups, users and devices complete from the tenant with the permissions already in hand — never a read on a keystroke without them, one enable-suggestions row when they are missing. Picking a user fills the UPN; the compare box completes the line the cursor is on; a pasted GUID is left alone. And every tool's read now shows one centred progress card — step, count when known — that never covers results already on screen." },
      { kind: "improved", tool: "🛡 Intune RBAC", text: "Role assignments becomes Intune RBAC, structured for growth: the same tool, renamed, with a section bar whose first section is role assignments — scope tags and further RBAC surfaces arrive there as sections rather than new tiles." },
    ],
  },
  {
    build: 7, date: "2026-08-24", title: "AppLocker becomes a migration workflow, and the header says who you are",
    items: [
      { kind: "fixed", tool: "TUNO", text: "The tenant identity in the header — your name, avatar and the Sign out button — has never been visible to anyone. The markup was there and the sign-in path switched it on by adding a class, but no rule in the stylesheet ever mentioned that class, so the box stayed hidden from the day TUNO was scaffolded. It renders now, and Sign out ends the session it always would have, had there been a button on screen to press. Signing in stays what it has always been here: a real interactive sign-in on every entry, with your identity provider re-running its whole policy. What did change underneath is that the permissions a tool asks for mid-session now arrive silently instead of prompting, and signing out fully clears the account so the next sign-in asks rather than silently continuing the session just ended." },
      { kind: "new", tool: "All tools", text: "What's new actually shows up: after sign-in, a dialog lists the releases newer than the last one you read, and only those. Nothing appears on a first visit, pressing Escape or clicking past it does not burn the notice, and reading the full list counts as reading. If your browser blocks site data the app simply shows it each session rather than breaking." },
      { kind: "new", tool: "🔐 AppLocker builder & validator", text: "The cleanup for devices that already have a policy. Two new scripts close the brownfield gap: one backs up the effective policy, the local policy and the registry tattoo, applies the genuinely inert empty policy, verifies the result and refuses to claim success when the device is still dirty; the other is the matching detection half for an Intune Remediation. Event logs survive by default, the AppID service is left alone, and the migration order — unassign, clean, deploy under a new grouping — is stated everywhere the work starts. Both are downloadable beside the scan in step 1." },
      { kind: "new", tool: "🔐 AppLocker builder & validator", text: "Remediations deploy from the browser. The cleanup pair and the IT-TOOLS folder provisioning pair can each be created in the signed-in tenant as an Intune Remediation — read-before-write, a stop on any name collision, created unassigned, with the standing-assignment advice stated per pair: the cleanup pair is for the migration window only, the folder pair is meant to stay. This is TUNO's second write permission and it is named in the open: creating Remediations needs its own scope, it has been added to the registration script and the security documentation, and an existing app registration needs the scope added and admin-consented before the button will work." },
      { kind: "new", tool: "🔐 AppLocker builder & validator", text: "The IT-TOOLS house convention, encoded rather than remembered: every generated policy carries standing allow rules for the ProgramData IT-TOOLS Apps and Scripts folders, the scan checks the ACL claim those rules rest on and raises a live-bypass warning when a folder inside them is user-writable, and a provisioning script creates the folders with inheritance disabled and admin-only writes — because ProgramData lets a standard user create a missing subfolder and own it, which would turn the standing allows into a hole. The LOGS folder deliberately has no rule, and the audit reports the house rules as information with their condition stated rather than arguing with its own defaults." },
      { kind: "fixed", tool: "🔐 AppLocker builder & validator", text: "The grouping guidance was wrong in the dangerous direction: it told you to reuse one grouping across the audit and enforce profiles, and Microsoft's documentation says grouping values must be unique — duplicates break deletion and unenrollment. Corrected everywhere it appeared, the instruction now being one profile edited in place; the grouping field generates its own unique identity instead of prefilling a reusable word, and typing one raises a visible warning. A new carry-over check also names every rule collection the device is already running that the policy on screen does not cover — the DLL question — and the CSP's automatic reboot on apply and on delete is finally documented." },
      { kind: "fixed", tool: "🔐 AppLocker builder & validator", text: "Three scan corrections. On PowerShell 7 the AppLocker module is now reached through the compatibility session with a timed budget, so publishers stop silently downgrading to certificate derivation where the proxy is fast enough — and the bundle records which source answered. Directories nested past the path-length limit are walked in extended form instead of silently dropping whole subtrees, with the unreadable counter split into four honest reasons. And the 5.1 rule-generation crash returned in a second shape — an indexed read this time — so every dictionary access on that path now goes through the one indexer the 5.1 binder cannot mischoose; the machine that failed twice has since completed the run." },
      { kind: "improved", tool: "🔐 AppLocker builder & validator", text: "A download can be one collection: a selector beside the button narrows the panel, the filename and the copy to a single rule collection, with the policy tab wrapping it as a complete importable policy and the Intune tab producing the bare collection an OMA-URI takes — two different artefacts, each the right one for its destination. The full-screen panels scroll to their last row, and in the split view the findings card shows a compact summary with the full table one click away." },
      { kind: "improved", tool: "All tools", text: "Help gained a table of contents — pills that jump to each section — and a section on what an AppLocker grouping actually is: an address rather than a label, why it must be unique, and why removal means unassignment. The app also knows its home tenant now and says so with a badge; on every other tenant the detection is a hidden span and nothing changes." },
    ],
  },
  {
    build: 6, date: "2026-08-21", title: "The AppLocker scan, corrected in the places that mattered",
    items: [
      { kind: "fixed", tool: "🔐 AppLocker builder & validator", text: "The generated policy was enforcing DLL control when it said it was not. The DLL section was written in the \"NotConfigured\" state and described everywhere as present but inert; Microsoft's own documentation says the opposite — rules in a collection that is not configured WILL be enforced, and the guidance is to avoid that state entirely. So a policy generated here would have blocked every DLL except the ones a single scan happened to find. The DLL section is now left out altogether, absence being the only genuinely inert state, and nothing generated by this tool is written as \"NotConfigured\" any more." },
      { kind: "fixed", tool: "🔐 AppLocker builder & validator", text: "The same misreading was giving the wrong verdict on policies you IMPORT, and this one may look like a regression when it is the correction. A section set to \"NotConfigured\" that carries rules was reported as unenforced, and the Microsoft app coverage table skipped it — so the tool could tell you OneDrive was fine on a policy that was blocking it. Enforcement is now judged by whether the section holds rules, and such a section is reported as a High finding that says plainly it is blocking today while reading as inactive. A section with no rules still reports as restricting nothing, as it always did." },
      { kind: "fixed", tool: "🔐 AppLocker builder & validator", text: "The device scan crashed at its final step and wrote nothing to disk, after the permission walk, the inventory and the event read had all completed — the whole run, discarded at the end. It was a PowerShell 5.1 expression-compiler fault in one line that stored a number into an ordered dictionary by index. Beyond the fix, rule generation is now wrapped: if it fails, the failure and the line it came from are recorded in the scan bundle and the bundle is written anyway. The evidence a scan gathers is worth keeping even when the policy it was going to build cannot be produced." },
      { kind: "improved", tool: "🔐 AppLocker builder & validator", text: "The scan states its central assumption and then checks it. An AppLocker policy built from a device means \"everything on this machine is allowed and nothing else is\", which is sound from a clean image and is a way of handing two years of accumulation back to yourself from a working laptop. The scan now looks for the tells of a used device — profile counts, Downloads and Desktop contents, browser profiles, per-user installs, developer folders — and a device that fails prints a stop-and-read block and appears as a High finding with the evidence quoted. A clean one is recorded as such." },
      { kind: "improved", tool: "🔐 AppLocker builder & validator", text: "The two routes software is legitimately installed by are now named in the generated policy rather than left to chance: explicit allow rules for the Intune Management Extension and its cache, in every rule collection, and the scan refuses to write an exception that would cut them out — a writable folder there becomes a warning instead of a hole punched through the delivery path. Breaking Company Portal installs or remediation scripts is the kind of failure that shows up days later and never gets traced back." },
      { kind: "new", tool: "🔐 AppLocker builder & validator", text: "A new AppLocker implementation checklist, downloadable beside the converter: every check that should pass before a policy is enforced, from reading the XML through coverage, the audit period, enforcement in rings, and living with it afterwards. Both PowerShell scripts also now state their own version and the site build that served them, in the banner and in the scan bundle, so a file that has been sitting on a share for six months can be traced back to what produced it." },
      { kind: "improved", tool: "🔐 AppLocker builder & validator", text: "The code panel, the findings table and the Microsoft coverage table each open full screen. The panel moves the card into it rather than copying it, so every button, filter and fix inside keeps working and applying a fix simply redraws the table in place. The code panel also stopped being the one thing on the page wearing a colour the product does not own." },
      { kind: "improved", tool: "All tools", text: "Eight more items on the roadmap, each crediting the community project behind it: bulk assignment editing, assignment what-if and health, a settings search across definitions, a wider and checkable backup, an offline comparison between two archives, copying configuration between tenants, and keeping the minimum OS version on compliance policies current. The security documentation also sets out why TUNO signs in with its own app registration rather than borrowing the identifier of Microsoft's Graph PowerShell tool, which several community tools do — for a program you install it is reasonable; for a web page it is refused outright, and it would put the wrong name on the consent record in your directory." },
    ],
  },
  {
    build: 5, date: "2026-08-20", title: "Four more tools, and the whole suite is production",
    items: [
      { kind: "new", tool: "\ud83d\udcc4 Configuration documenter", text: "Every policy in the tenant on one page, filterable by name, by any setting inside it, by platform and by whether it is assigned to anything at all \u2014 and the same read turned into a document, as Markdown for a wiki, a standalone HTML page that opens anywhere and prints cleanly, or Word for the auditor who is going to edit it. Secret-bearing values are redacted and there is deliberately no way to turn that off: this is the most widely circulated thing the tool can produce, and a key that goes into a shared drive cannot be recalled. The exports follow what you have ticked, not what you have filtered, and every export header states how many of how many objects it holds so a partial document can never be mistaken for a complete one." },
      { kind: "new", tool: "\ud83d\udda5 Device analyzer", text: "Name a device and it says why it gets what it gets: every policy that reaches it, whether through a group, through the user, or tenant-wide, with what Intune INTENDED beside what the device actually REPORTED. Press a policy name and its settings open underneath, so the question of what a policy actually sets is answered where it is asked rather than in another tool." },
      { kind: "new", tool: "\ud83d\udce6 Backup configuration", text: "Everything Intune holds as configuration read out and written to one zip file in this tab \u2014 profiles, settings catalog policies with their settings, compliance policies with their scheduled actions, administrative templates with their definition values, and scripts with their bodies. Nothing is uploaded and nothing is stored. The folder and file names match the PowerShell original exactly, deliberately: restore is driven by folder names, so an archive written here can be restored by that script and one written by it can be read back here." },
      { kind: "new", tool: "\ud83d\udee1 Role assignments", text: "Who can change Intune, and over which devices. Every role definition and assignment, with members, scope groups and scope tags resolved to names rather than left as identifiers. Observations rather than a score: what the tool reports are facts about the tenant, and grading them would need a policy it has no way to know." },
      { kind: "fixed", tool: "All tools", text: "Granting a permission no longer walks you through multi-factor authentication. The consent window was being opened with an instruction that re-authenticates as well as re-consents, so what should be one click on a screen listing what is being asked for became a full sign-in. Permissions are still asked for at the moment they are used, never at sign-in." },
      { kind: "improved", tool: "All tools", text: "The summary strips at the top of each tool read as strips rather than boxes with their contents pressed against the frame, and the result cards below them have the padding they always should have had." },
    ],
  },
  {
    build: 4, date: "2026-08-20", title: "Two tools that read the tenant",
    items: [
      { kind: "new", tool: "\ud83d\udd17 Group Analyzer", text: "The second tool, and the first that reads your tenant rather than a file you gave it. Name a group and it answers what Intune actually does with it: enrolment restrictions, compliance, configuration profiles, scripts and remediations, app protection and app configuration, app assignments, Autopilot and update rings \u2014 with each surface read separately, so one that cannot be read is reported as unknown rather than counted as empty. There is also a tenant sweep across every group Intune assigns to, with the counts per surface and the dangling references \u2014 assignments naming a group the directory no longer has, which target nobody and which nothing in the portal will tell you about." },
      { kind: "new", tool: "\ud83d\udd53 Change audit", text: "The third tool. Somebody changed something and a fleet of devices behaved differently the next morning \u2014 this reads the tenant's own audit log and says who, what, when and from where, with the field-level detail of what actually moved. Two views over one read: policy changes with a severity on each event, and every category with filters on actor, activity, category and result. Filters apply to what has already been read, so changing one costs nothing and asks the tenant nothing. Intune keeps thirty days; anything older is gone from the service and the tool says so rather than showing an empty result." },
      { kind: "improved", tool: "All tools", text: "Both read only, and both ask for their permissions at the moment you use them rather than at sign-in. A surface that could not be read is named as unread everywhere it appears \u2014 in the counts, in the exports and in the prose \u2014 because a zero that means 'nothing here' and a zero that means 'nobody looked' are different answers and only one of them is safe to act on." },
      { kind: "improved", tool: "All tools", text: "One column width across the whole app, and the Help page reordered to read top to bottom instead of by the order the sections were written. The setup script also stopped rewriting its own instructions each time it ran." },
    ],
  },
  {
    build: 3, date: "2026-08-20", title: "The AppLocker tool grew up",
    items: [
      { kind: "improved", tool: "\ud83d\udd10 AppLocker builder & validator", text: "It was a policy reader. It is now the whole job, in five steps. SCAN: the tool hands you Invoke-TunoAppLockerScan.ps1, run once on a representative device, elevated. A browser cannot read a directory permission, verify a signature or open an event log, and those three facts are most of what decides whether an AppLocker policy is sound \u2014 a rule allowing the Program Files folder is only as strong as the permissions underneath it, and the XML does not say what those are. The scan does, and every verdict that came from it is marked so you can see which half of the analysis proved what. UPLOAD: the same button takes the scan bundle or a plain policy XML, so the scan is optional and skipping it costs you only the evidence a browser cannot gather. REVIEW, EXPORT, DEPLOY follow." },
      { kind: "improved", tool: "\ud83d\udd10 AppLocker builder & validator", text: "Every finding that ends in a recommendation now carries a button that performs it. Mechanical ones apply in a click \u2014 set an enforcement mode, add the Microsoft default rules, add a collection the XML never mentioned. Ones needing a fact the tool does not have open the offending rule prefilled, so you supply the publisher, the version bound or the purpose-built group, and it refuses to invent any of them. Every change leaves one step back, named for what it did." },
      { kind: "improved", tool: "\ud83d\udd10 AppLocker builder & validator", text: "Enforcement is never switched on for you. The only mode change the tool makes by itself is the one that blocks nothing: a collection with no rules is offered AuditOnly or the default rules first, never a straight Enable, because enabling it would block every file of that type. Going from AuditOnly to Enabled opens a panel listing what should be true first \u2014 time in audit across a month-end, a patch cycle and a new starter; an event log with nothing unrecognised left; a coverage table reading allowed; a tested way back \u2014 and you choose." },
      { kind: "new", tool: "\ud83d\udd10 AppLocker builder & validator", text: "The policy XML is on screen while you edit it, in a panel of its own, redrawn on every change and rendered from the same code that writes the download \u2014 so the preview cannot drift from the file. A second tab carries the Intune custom profile built from the same serialiser, and step 5 can create that profile in your tenant directly, under rules narrower than the permission allows: nothing is overwritten, assignment is a separate act that tells you how many people it reaches, and the Enforce profile stays locked until an uploaded scan shows nothing was blocked and nothing would have been." },
      { kind: "new", tool: "All tools", text: "TUNO has its own mark \u2014 header, sign-in and favicon \u2014 instead of wearing ENCA's. Every artwork reference carries a version, so a browser that has seen the old one does not keep it." },
      { kind: "improved", tool: "All tools", text: "ENCA's tab bar, ported: a home button, a pill for each tool you have opened with its own close cross, a plus menu, close-all once two are open, and Help pinned right. Hidden on the tools home, because there is nothing to switch between there." },
      { kind: "new", tool: "All tools", text: "A Microsoft Graph layer, which TUNO did not have. Scopes are requested per capability at the moment you use one, never at sign-in \u2014 reading a policy XML in your own browser should not buy the right to change anything. A refusal comes back in the tenant's own words with its error code and request id, and an administrator-consent link when that is what is missing." },
      { kind: "improved", tool: "All tools", text: "New-TunoAppRegistration.ps1 declares every permission the tools can ask for, each with a note saying which tool needs it, and its redirect-URI list now carries every host TUNO is served from \u2014 the list replaces rather than merges, so a host missing from it was a host the next run would have deleted." },
    ],
  },
  {
    build: 2, date: "2026-08-19", title: "Sign-in works — the app registration exists",
    items: [
      { kind: "new", tool: "All tools", text: "The TUNO (Limon-IT) app registration is live and js/authConfig.js carries its client ID, so the sign-in screen signs in instead of explaining why it cannot. Multi-tenant SPA, authorization code + PKCE, no client secret; delegated User.Read plus SecurityEvents.Read.All consented up front so the Secure Score visualizer (roadmap R02) can ask for it on the click when it lands. Created by New-TunoAppRegistration.ps1, which also patched this config." },
    ],
  },
  {
    build: 1, date: "2026-08-19", title: "TUNO exists — and it opens with AppLocker",
    items: [
      { kind: "new", tool: "AppLocker builder & validator", text: "TUNO's first tool, in BETA. Import an AppLocker policy XML — a GPO export or the output of Get-AppLockerPolicy -Effective -Xml — and it is audited in the browser with the AppLockerInspector check set: collections left NotConfigured or AuditOnly, allow rules granted to Everyone / Authenticated Users / BUILTIN-Users, paths under user-writable trees (profiles, AppData, Temp, Downloads, ProgramData), drive-root and wildcard patterns, UNC allows, publisher rules with any-product / any-binary / no upper version bound, and hash rules assigned to broad principals — each finding with a severity, the reason and a recommendation, and an allow that a deny rule provably shadows is skipped rather than reported. After Spencer Alessi's AppLockerInspector; the NTFS and share ACL reality checks need a filesystem and stay in his PowerShell — the report says which checks did not run here rather than pretending they did." },
      { kind: "new", tool: "AppLocker builder & validator", text: "The Microsoft coverage check — the question every locked-down estate discovers too late: are the Microsoft apps people actually use still allowed to run? A catalog of the ones that bite (OneDrive's per-user install under AppData first among them, plus Teams, Edge WebView2, Office click-to-run and the servicing executables) is evaluated against the imported policy the way AppLocker itself would decide — deny beats allow, exceptions respected, path macros expanded, publisher fields matched — and every app comes back allowed, blocked, or allowed only through a rule the audit flags as risky. A blocked app gets a one-click fix: the publisher rule (path fallback where signing is inconsistent) added to the policy." },
      { kind: "new", tool: "AppLocker builder & validator", text: "The builder half: start from the imported policy or from empty, add the Microsoft-recommended default rules per collection, set enforcement modes, add publisher / path / hash rules by hand, delete what should not be there — and export the result as AppLocker policy XML that imports straight back into a GPO, plus a Markdown findings report for the change ticket. Everything runs in the browser; the XML never leaves the machine." },
      { kind: "new", tool: "All tools", text: "The TUNO shell itself, built as ENCA's sister: same layout, same branding, same sign-in model (a SPA using authorization code + PKCE, no client secret, single-tenant registration supported via New-TunoAppRegistration.ps1), same two-series build numbering, same changelog / roadmap / promotion-queue discipline, and the same BETA ribbon on any host that is not tuno.limon-it.nl." },
    ],
  },
];
